apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskflow-data-pvc
  labels:
    app: taskflow-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
