apiVersion: v1
kind: Service
metadata:
  name: taskflow-api
  labels:
    app: taskflow-api
spec:
  type: NodePort
  selector:
    app: taskflow-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
